#!/bin/sh

usage()
{
cat << EOF
usage: $0 WAKETIME [SLEEPDELAY]

Wake up the computer at the given time using the ACPI RTC interface
Run a command 2 minutes later.
Optionally go to sleep after a delay.
EOF
}

WAKETIME=$1
if [ "$2" ]
then
  SLEEP=1
  SLEEPDELAY=$2
fi

if [ -z "$WAKETIME" ]
then
     usage
     exit 1
fi

# clear the alarm
sudo sh -c 'echo 0 > /sys/class/rtc/rtc0/wakealarm;
echo `date "+%s" -d "$WAKETIME"` > /sys/class/rtc/rtc0/wakealarm'

# PLAYCMD="banshee --play"
PLAYCMD="rhythmbox-client --next"
echo "$PLAYCMD" | at $WAKETIME + 2 minutes

# various sleep commands
# see http://www.uluga.ubuntuforums.org/showthread.php?t=813387&page=5
# lucid+, non-root
SLEEPCMD="dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend"
#/etc/acpi/sleep.sh sleep

if [ "$SLEEP" ]
then
  if [ "$SLEEPDELAY" ]
  then
    echo "$SLEEPCMD" | at now + "$SLEEPDELAY"
  else
    $SLEEPCMD
  fi
fi
